## Linear Algebra and Multivariable Calculus Self Assessment

You can use numpy (or other software which supports linear algebra) to assist with any linear algebra computations.  

If you are *extremely* sure that you can do these computations, you should just skim over the solutions and confirm that they make sense to you.  If you are confident that you could produce solutions which are of comparable or superior quality then the Linear Algebra and Multivariable Calculus parts of the Crash Course are probably not worth your time!

1. Compute the total derivative $Df$ of the function $f: \mathbb{R}^2 \to \mathbb{R}^3$ defined by $f(x,y) = (xy, x, x^2-y^2)$.  Use the linear approximation of $f$ at $(1,2)$ to approximate $f(1.01, 1.99)$.
2. Consider the function $f: \mathbb{R}^3 \to \mathbb{R}$ defined by $f(x,y,z) = x^2 + y^2 +z^2 - xy - 2x + 3y + z + 1$. Find the stationary points of $f$. Determine whether the Hessian is positive definite, positive semi-definite, negative semi-definite, negative definite, or none of the above.  What does this tell you about the stationary points:  are they local maxima, local minima, or saddle points?

* Note:  The first two questions deal with multivariable differential calculus and optimization.  Many data science techniques involve specifying a model as a function of some parameters, and minimizing a loss function with respect to these parameters to "fit" the model.  An understanding of multivariate differential calculus is essential for really understanding what is happening with these techniques.  For instance: linear regression, logistic regression, support vector machines, and training a neural network all depend on minimizing a loss function of some parameters.

3.  Project the vector $ \vec{y} = \begin{bmatrix}  1 \\ 2 \\ 3\end{bmatrix}$ orthogonally onto the image of the linear transformation with matrix $A = \begin{bmatrix} 1 & 2 \\ 1 & 3 \\ 1 & -1  \end{bmatrix}$.  

4. Find the Singular Value Decomposition of the matrix $\begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6\end{bmatrix}$.  Use the SVD to find a rank 1 approximation of the matrix.

* Note:  Singular Value Decomposition is essential for understanding principle component analysis, which is an important dimension reduction technique often used in data science.

Paul Rapoport's Answers:

1. 
$$
\begin{align*}
Df &= [[\partial f_1/\partial x, \partial f_1/\partial y], [\partial f_2/\partial x, \partial f_2/\partial y], [\partial f_3/\partial x, \partial f_3/\partial y]]\\
&= [[y, x],[1, 0],[2x, -2y]]\\

L_{(1, 2)}f(x) &= f(1, 2) + Df(1, 2) \cdot (x - (1, 2))\\
&= [2, 1, -3] + [[2, 1],[1, 0],[4, -2]] \cdot [0.01, -0.01]\\
&= [2, 1, -3] + [0.02 - 0.01, 0.01 + 0, 0.04 + 0.02]\\
&= [1.99, 0.99, -2.94]
\end{align*}
$$

2. We want: $ \partial f / \partial x = \partial f / \partial y = \partial f / \partial z = 0 $. Calculating this out, we have $ \partial f / \partial x = 2x - y - 2, \partial f / \partial y = 2y - x + 3, \partial f / \partial z = 2z + 1$. Then $ z = \frac{1}{2}$, and we have a system of equations $2x - y = 2, -x + 2y = -3$, which has solution $x = \frac{1}{3}, y = -\frac{4}{3}$, that is, the unique stationary point is at $(\frac{1}{3}, -\frac{4}{3}, \frac{1}{2})$.\\
We form the Hessian $\mathcal{H}f$ as the matrix of all possible second derivatives, which will be symmetric; it thus suffices to check the eigenvalues of $\mathcal{H}f(1, 2)$ in order to check for sign-definiteness; in fact, since all second partial derivatives of $f$ are constant, it suffices to check this for the (constant) general Hessian. We have:
$$
\mathcal{H}f =
\begin{bmatrix}
2 & -1 & 0 \\
-1 & 2 & 0 \\
0 & 0 & 2 
\end{bmatrix}
$$
so that eigenvalues are given by solutions to
$$
\begin{align*}
\big\vert \mathcal{H}f - \lambda I \big\vert &= 0\\
(2-\lambda)((2-\lambda)^2 - 1) &= 0\\
(2-\lambda)(2 - 2\lambda + \lambda^2 - 1) = (2-\lambda)(3 - 2\lambda + \lambda^2) &= 0\\
(2-\lambda)(1 - \lambda)(3 - \lambda) &= 0,
\end{align*}
$$
that is, $ \lambda \in \{1, 2, 3\} $. We could solve for the eigenvectors now if we chose, but we don't have to; we already have enough to know that the Hessian is positive-definite and thus that our stationary point is a local (and probably global) minimum.

3. For projection vector $\vec{p}_y$, we want for two things to be true: that for some $\vec{x} \in \mathbb{R}^2$, $A\vec{x} = \vec{p}_y$, and that $A^T (\vec{y} - \vec{p}_y) = \vec{0}$, that is, that $\vec{p}_y$ is in the image of the (invertible) linear map that $A$ represents, and that $(y - \vec{p}_y)$ is orthogonal to the image of $A$ (this last because $A^TA\vec{v} = A^T \vec{w}$ so that a vector being orthogonal to the image of $A$ is the same as $A^T$ taking the vector to the zero vector). Thus we have:
$$
\begin{align*}
A^T (\vec{y} - A\vec{x}) &= \vec{0}\\
A^T \vec{y} - A^TA\vec{x} &= \vec{0}\\
A^TA\vec{x} &= A^T \vec{y}\\
\vec{x} &= (A^TA)^{-1}A^T \vec{y}\\
A\vec{x} &= A(A^TA)^{-1}A^T \vec{y}\\
\end{align*}
$$



In [25]:
import numpy as np
from numpy import linalg
mat_A = np.array([[1, 2], [1, 3], [1, -1]])
vec_y = np.array([1, 2, 3]).T

# print(np.shape(np.matmul(linalg.inv(np.matmul(mat_A.T, mat_A)), mat_A.T)))

proj_mat = np.matmul(linalg.inv(np.matmul(mat_A.T, mat_A)), mat_A.T)  # important to use matmul here - the default is elementwise! 
print(proj_mat, np.shape(proj_mat))
vec_x = np.matmul(proj_mat, vec_y)
print(vec_x, np.shape(vec_x))
proj_vec = np.matmul(mat_A, vec_x)
print('p_y =', proj_vec)

[[ 0.23076923  0.07692308  0.69230769]
 [ 0.07692308  0.19230769 -0.26923077]] (2, 3)
[ 2.46153846 -0.34615385] (2,)
p_y = [1.76923077 1.42307692 2.80769231]


4. Let $$ B = \begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6 
\end{bmatrix}. $$
We want to find the SVD of $B = U\Sigma V^T$. To do this, we'll start by finding the eigenvalues of $BB^T$ and take their square roots, which will give us $\Sigma$. We have
$$
BB^T=
\begin{bmatrix}
5 & 11 & 17 \\
11 & 25 & 39 \\
17 & 39 & 61 
\end{bmatrix}

(maybe I want to do #4 primarily in code instead?)

## Answers to Self Assessment

> 1. Compute the total derivative $Df$ of the function $f: \mathbb{R}^2 \to \mathbb{R}^3$ defined by $f(x,y) = (xy, x, x^2-y^2)$.  Use the linear approximation of $f$ at $(1,2)$ to approximate $f(1.01, 1.99)$.

$$
\begin{align*}
Df\big\vert_{(x,y)} 
&= 
\begin{bmatrix} 
\frac{\partial}{\partial x} (xy) & \frac{\partial}{\partial y} (xy) \\
\frac{\partial}{\partial x} (x) & \frac{\partial}{\partial y} (x) \\
\frac{\partial}{\partial x} (x^2 - y^2) & \frac{\partial}{\partial y} (x^2 - y^2) \\
\end{bmatrix}\\
&= 
\begin{bmatrix} 
y & x \\
1 & 0 \\
2x & -2y \\
\end{bmatrix}\\
\end{align*}
$$

So 

$$
Df\big\vert_{(1,2)} 
= 
\begin{bmatrix} 
2 & 1 \\
1 & 0 \\
2 & -4 \\
\end{bmatrix}\\ 
$$

So 

$$
\begin{align*}
f(1.01, 1.99) 
&= f( (1,2) + \begin{bmatrix} 0.01 \\ -0.01\end{bmatrix})\\
&\approx f(1,2) + Df\big\vert_{(1,2)}\begin{bmatrix} 0.01 \\ -0.01\end{bmatrix}\\
&= (2,1,-3) + \begin{bmatrix} 
2 & 1 \\
1 & 0 \\
2 & -4 \\
\end{bmatrix}\begin{bmatrix} 0.01 \\ -0.01\end{bmatrix}\\
&=(2,1,-3) + \begin{bmatrix}0.01 \\ 0.01\\ -0.02 \end{bmatrix}\\
&= (2.01, 1.01, -2.94)
\end{align*}
$$

We can check this against the exact value $f(1.01, 1.99) = (2.0099, 1.01, -2.94)$ which is very close!

> 2. Consider the function $f: \mathbb{R}^3 \to \mathbb{R}$ defined by $f(x,y,z) = x^2 + y^2 +z^2 - xy - 2x + 3y + z + 1$. Find the stationary points of $f$. Determine whether the Hessian is positive definite, positive semi-definite, negative semi-definite, negative definite, or none of the above.  What does this tell you about the stationary points:  are they local maxima, local minima, or saddle points?


The gradient of $f$ is 

$$
\begin{align*}
\nabla f &= \begin{bmatrix}  \frac{\partial f}{\partial x} \\ \frac{\partial f}{\partial y} \\ \frac{\partial f}{\partial z}\end{bmatrix}\\
&= \begin{bmatrix} 2x - y - 2 \\ 2y - x + 3  \\ 2z + 1\end{bmatrix}
\end{align*}
$$

So the gradient is 0 when 

$$
\begin{cases}
2x - y = 2 \\ 2y - x   = -3 \\ 2z =  -1
\end{cases}
$$

We could solve this system by hand, but I will use numpy:

In [2]:
M = np.array([[2, -1, 0 ],[-1, 2, 0],[0, 0, 2]])
stationary_point = np.dot(linalg.inv(M), [[2],[-3],[-1]])
print('The stationary point is \n', stationary_point)

The stationary point is 
 [[ 0.33333333]
 [-1.33333333]
 [-0.5       ]]


The Hessian matrix is 

$$
\begin{align*}
\mathcal{H}f 
&= 
\begin{bmatrix} 
\frac{\partial^2 f}{\partial x^2} & \frac{\partial^2 f}{\partial y \partial x} & \frac{\partial^2 f}{\partial z \partial x}\\
\frac{\partial^2 f}{\partial x \partial y} & \frac{\partial^2 f}{\partial y^2} & \frac{\partial^2 f}{\partial z \partial y}\\
\frac{\partial^2 f}{\partial x \partial z} & \frac{\partial^2 f}{\partial y \partial z} & \frac{\partial^2 f}{\partial z^2}\\
\end{bmatrix}
\\
&=
\begin{bmatrix} 
2 & -1 & 0\\
-1 & 2 & 0\\
0 & 0 & 2\\
\end{bmatrix}
\end{align*}
$$

We need to check the definiteness of this matrix.

This is actually easy enough to do by inspection:  

* $\begin{bmatrix} 0 \\ 0 \\ 1\end{bmatrix}$ is an eigenvector with eigenvalue $2$
* $\begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}$ is an eigenvector with eigenvalue $1$. 

 Since the trace is $6$, we must have another eigenvector with eigenvalue $3$, so this matrix is positive definite.  Thus the critical point $(\frac{1}{3}, -\frac{4}{3}, -\frac{1}{2})$ is where the global minimum value of this function occurs.  

Addendum:  Oh, I see it now:  the eigenvector $\begin{bmatrix} 1 \\ -1 \\ 0 \end{bmatrix}$ has eigenvalue $3$.  Actually, we should have anticipated this, since by the real spectral theorem the eigenvectors of a symmetric matrix must be orthogonal.  Thinking geometrically, this vector must have been in the $xy$ plane to be orthogonal to the first eigenvector, and then to be perpendicular to $\begin{bmatrix} 1 & 1 & 0 \end{bmatrix}^\top$ it had to be $\begin{bmatrix} 1 & -1 & 0 \end{bmatrix}^\top$!

Let's double check ourselves with numpy:

In [3]:
H = np.array([[2,-1,0],[-1,2,0],[0,0,2]])

# linalg.eig is a function which takes a matrix and returns a tuple of arrays. The index 0 element of the tuple is the array of eigevalues.
# the index 1 tuple is the matrix whose columns are eigenvectors.

print('The eigenvalues are ', linalg.eig(H)[0])
print('The eigenvectors are the columns of \n', linalg.eig(H)[1])
print('These are the same eigenvectors we found, just normalized')

The eigenvalues are  [3. 1. 2.]
The eigenvectors are the columns of 
 [[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
These are the same eigenvectors we found, just normalized


> 3.  Project the vector $ \vec{y} = \begin{bmatrix}  1 \\ 2 \\ 3\end{bmatrix}$ onto the image of the linear transformation with matrix $A = \begin{bmatrix} 1 & 2 \\ 1 & 3 \\ 1 & -1  \end{bmatrix}$

There are several approaches.  In this case, when the dimension of the image is low, it is not unreasonable to use the Gram–Schmidt process to find an orthonormal basis of the image, and then project $\vec{y}$ onto the span of each basis vector.
<br>
I will take a different approach, which gives an explicit formula for the projection in terms of $A$ and $\vec{y}$.  
<br>
Call the projected vector $\vec{p}$.  Then we want $\vec{p}$ to be in the image of $A$ so $\vec{p} = A\vec{x}$ for some $\vec{x} \in \mathbb{R}^2$.  We also want $\vec{y} - \vec{p}$ to be perpedicular to the image of $A$.  So we want $A^\top (\vec{y} - \vec{p}) = \vec{0}$.
<ve>
Putting this together we have 
<br>
$$
\begin{align*}
& A^\top (\vec{y} - A\vec{x}) = \vec{0}\\
& A^\top A\vec{x} = A^\top \vec{y}\\
& \vec{x} = (A^\top A)^{-1} (A^\top \vec{y}), \textrm{see Note}\\
& A \vec{x} = A (A^\top A)^{-1} (A^\top \vec{y})\\
& p = A (A^\top A)^{-1} (A^\top \vec{y})
\end{align*}
$$

Note 1:  $(A^\top A)$ is invertible when $A$ has linearly independent columns, which holds in our example.

Note 2:  This is the "normal equation" for least squares linear regression!  We will see that connection spelled out in a later notebook.

We could do this by hand since $A$ is just a $3 \times 2$ matrix, but I will use numpy:

In [24]:
y = np.array([[1],[2],[3]])
A = np.array([[1,2],[1,3],[1,-1]])
Aty = np.dot(A.transpose(),y) # A-tranpose times y
AtAinv = linalg.inv(np.dot(A.transpose(), A)) # the inverse of A-tranpose times A.
p = np.dot(A, np.dot(AtAinv, Aty)) # writing out the formula we found.
print(p)

[[1.76923077]
 [1.42307692]
 [2.80769231]]


In [5]:
# Let's check that y - p is perpendicular to both columns of A.  It is clearly in the image of A since it is defined as A applied to a vector.
# Rounded to 10 place values, these dot products are both 0.

round(np.dot(A[:,0].reshape(1,3),(y-p))[0,0],10), round(np.dot(A[:,1].reshape(1,3),(y-p))[0,0],10)

(-0.0, -0.0)

> 4. Find the singular value decomposition of the matrix $A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6\end{bmatrix}$.  Use the SVD to find a rank 1 approximation of the matrix.

In [6]:
A = np.array([[1,2],[3,4],[5,6]])

In [7]:
linalg.svd(A)

SVDResult(U=array([[-0.2298477 ,  0.88346102,  0.40824829],
       [-0.52474482,  0.24078249, -0.81649658],
       [-0.81964194, -0.40189603,  0.40824829]]), S=array([9.52551809, 0.51430058]), Vh=array([[-0.61962948, -0.78489445],
       [-0.78489445,  0.61962948]]))

In [8]:
# U is self-explanatory
U = linalg.svd(A)[0]

# Looking at the documentation, S is the vector of singular values. 
# We actually want the matrix with appropriate dimension.  Using np.diag(linalg.svd(A)[1]) gives us a 2x2 matrix. 
# To make it 2 x 3 we need to pad that with a row of zeros at the bottom.

S = np.pad(np.diag(v=linalg.svd(A)[1]),pad_width=[(0,1),(0,0)], mode='constant', constant_values=0)

# The method returns V tranpose, not V.

V = linalg.svd(A)[2].transpose()

# Check that it works:

print("U = \n", U)
print("S = \n", S)
print("V = \n", V)
print("USV^t = \n", U @ S @ V.transpose())

U = 
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
S = 
 [[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]
V = 
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
USV^t = 
 [[1. 2.]
 [3. 4.]
 [5. 6.]]


The rank 1 approximation of $A$ is just $U \Sigma V^\top$, but replacing the smaller of the two eigenvalues with $0$.  So our rank $1$ approximation of $A$ is:

In [9]:
rank_1_approx = U  @ (S * [1,0]) @ V.transpose()
print(rank_1_approx)

[[1.35662819 1.71846235]
 [3.09719707 3.92326845]
 [4.83776596 6.12807454]]


Observe that rank_1_approx is close to $A$, but its second column is a multiple of its first column:

In [10]:
print('These values should all be the same:', rank_1_approx[:,1]/rank_1_approx[:,0])

These values should all be the same: [1.26671579 1.26671579 1.26671579]
